[profile.dev]
overflow-checks = false     # Disable integer overflow checks.

[workspace]
members = [
    "entity",
    "pitch",
    "render",
    "rest_note_chord",
    "rhythm",
    "staff",
    "stencil",
]
