[package]
name = "pitch"
version = "0.1.0"
authors = ["Joshua Netterfield <joshua@nettek.ca>"]
edition = "2018"
license = "AGPL-3.0-or-later"
description = "Note names and accidentals"
repository = "https://github.com/jnetterf/six"

[dependencies]
wasm-bindgen = "0.2.59"
