[package]
name = "entity"
version = "0.1.0"
authors = ["Joshua Netterfield <joshua@nettek.ca>"]
edition = "2018"
license = "AGPL-3.0-or-later"
description = "A lightweight ECS"
repository = "https://github.com/jnetterf/six"

[dependencies]
