[package]
name = "render"
version = "0.1.0"
authors = ["Joshua Netterfield <joshua@nettek.ca>"]
edition = "2018"

[dependencies]
entity = { path = "../entity" }
rest_note_chord = { path = "../rest_note_chord" }
rhythm = { path = "../rhythm" }
stencil = { path = "../stencil" }
kurbo = {git = "https://github.com/linebender/kurbo", rev = "680b4a94d11db6d59e2be323dee721d9bd25ae56"}

[dependencies.num-rational]
version = "0.2.2"
default-features = false
