[package]
name = "stencil"
version = "0.1.0"
authors = ["Joshua Netterfield <joshua@nettek.ca>"]
edition = "2018"

[dependencies]
kurbo = {git = "https://github.com/jnetterf/kurbo", branch = "last_ctrl"}
